spring:
  name: thumb-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thumb_db
    username: root
    password: 1234
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 2
      timeout: 5000
  # sesion
  session:
    store-type: redis
    # 30天过期
    timeout: 259200
server:
  port: 8123
  servlet:
    context-path: /api
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yukina.thumbbackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn





